version: '3'

services:
  fastapi-template:
    container_name: fastapi-template
    build: .
    image: fastapi-template:latest
    restart: always
    env_file:
      - .env
    network_mode: host
    ports:
      - 5000:5000
